version: '3'
services:
  backend:
    build: ./flask_app
    ports:
      - "5000:5000"

  frontend:
    build: ./react_app
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend